config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :pins
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'mypins' => 'pins#mypins'
  get 'pinsoff/:user_id' => 'pins#pinsoff', :as => "pinsoff"

  #Salir
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  validates :photo, presence:true
  validates :description, presence:true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :phone])
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[ :index, :show ]


  def mypins
    @pins = current_user.pins
  end

  def pinsoff
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @pins = @user.pins 
  end
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
      @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPinterest</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <%= stylesheet_link_tag    '/assets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '/assets/application', 'data-turbolinks-track': 'reload' %>



    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
  </head>

  <body>

<%= render 'shared/navbar' %>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name,  :class=> 'form-control' %>
      </div>
    </div>
<div class="form-group">
  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :pin_photo, :class=> 'form-control' %>
  </div>
</div>
    <div class="form-group">
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :pin_description, :class=> 'form-control' %>
  </div>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
  <h1>Editar el Pin</h1>
<div class="row">
  <div class="col-md-6">
<%= render 'form', pin: @pin %>
  </div>
</div>
<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>


<div id="container">
 <h1>Pins</h1>
  <% @pins.each do |pin| %>
<div class="item" style="width:25%">
  <div class="thumbnail">
    <%= pin.name %>
    <%= image_tag( pin.photo, :class => 'img-responsive') %>
    <%= pin.description %>
     <div class="buttons", style="margin-top:10px; margin-bottom:10px ">
        <%= link_to 'Show', pin , :class => 'btn'%>
        <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
        <% if user_signed_in? %>
        <%= link_to 'Destroy', pin, :method=> :delete, data: { confirm: 'Are you sure?' }, :class => 'btn'  %>
        <% end %>
     </div>
   </div>
</div>
    <% end %>
<br>
<% if user_signed_in? %>
<%= link_to 'New Pin', new_pin_path %>
<% end %>
</div>

<script type="text/javascript">
    var $container = $('#container')
        // options
        $container.masonry({
        columnWidth: 200,
        itemSelector: '.item'
    });

  $(window).load(function(){
    var $container = $('#container');
        // options
      $container.masonry({
          columnWidth: 200,
          itemSelector: '.item'
    });
  })
</script>

app/views/pins/mypins.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
 <h1>Mis Pins</h1>
  <% @pins.each do |pin| %>
<div class="col-md-3">
  <div class="thumbnail">
    <%= pin.name %>
    <%= image_tag( pin.photo, :class => 'img-responsive') %>
    <%= pin.description %>
     <div class="buttons", style="margin-top:10px; margin-bottom:10px ">
        <%= link_to 'Show', pin , :class => 'btn'%>
        <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
        <% if user_signed_in? %>
        <%= link_to 'Destroy', pin, :method=> :delete, data: { confirm: 'Are you sure?' }, :class => 'btn'  %>
        <% end %>
     </div>
   </div>
</div>
    <% end %>
<br>
<% if user_signed_in? %>
<%= link_to 'New Pin', new_pin_path %>
<% end %>
</div>

app/views/pins/new.html.erb
<div class="container">
<h1>Crear un nuevo pin</h1>
<div class="col-md-6">
  <div  class="row">
<%= render 'form', pin: @pin %>
</div>
<%= link_to 'Back', pins_path %>
</div>
</div>

app/views/pins/pinsoff.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
 <h1>Mis Pins</h1>
  <% @pins.each do |pin| %>
<div class="col-md-3">
  <div class="thumbnail">
    <%= pin.name %>
    <%= image_tag( pin.photo, :class => 'img-responsive') %>
    <%= pin.description %>
     <div class="buttons", style="margin-top:10px; margin-bottom:10px ">
        <%= link_to 'Show', pin , :class => 'btn'%>
        <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
        <% if user_signed_in? %>
        <%= link_to 'Destroy', pin, :method=> :delete, data: { confirm: 'Are you sure?' }, :class => 'btn'  %>
        <% end %>
     </div>
   </div>
</div>
    <% end %>
<br>
<% if user_signed_in? %>
<%= link_to 'New Pin', new_pin_path %>
<% end %>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pin.name %>
</p>
<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style =>'width:200px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

<%= link_to "Mas pins del mismo usuario", pinsoff_path(@pin.user.id) %>

app/views/shared/_navbar.html.erb

<nav class="navbar navbar-default " role="navigation" style="margin-bottom:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand" href="<%= root_path %>">Mi Pinteres</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Nosotros</a></li>
        <li><a href="<%= mypins_path %>">Mis Pins</a></li>
        <li><a href="<%= pins_path %>">Pins</a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
      <% if current_user.nil? %>
        <li><a href="<%= new_user_session_path %>">Ingreso</a></li>
        <li><a href="<%= new_user_registration_path %>">Registro</a></li>
        <% else %>
        <li><a href="<%= destroy_user_session_path %>" data-method="delete">Salir</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <p> Imagenes de</p>
    <h1 class="titulo">Resident Evil</h1>
    <a href="http://en1mes.com" target="_blank" class="btn btn-default">
      En1Mes
      <span class="glyphicon glyphicon-eye-open" style=" color:green"></span>
    </a>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="page-header">
        <h2 style="display:inline"> lorep isum</h2>
        <span class="label label-default">New</span>
      </div>

      <a href="http://en1mes.com">En1Mes</a>
      <a href="http://en1mes.com" target="_blank">En1Mes</a>
      <p>Lorem Ipsum is simply dummy text of
        the printing and typesetting industry.
        Lorem Ipsum has been the industry's standard dummy
        text ever since the 1500s, when an unknown printer
        took a galley of type and scrambled it to make a type specimen book.
        It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of
        Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
        software like Aldus PageMaker including versions of Lorem Ipsum.</P>


    </div>
    <div class="col-md-4">
      <div class="page-header">
        <h2>Subtitulos</h2>
      </div>
      <p>Lorem Ipsum is simply dummy text of
        the printing and typesetting industry.
        Lorem Ipsum has been the industry's standard dummy
        text ever since the 1500s, when an unknown printer
        took a galley of type and scrambled it to make a type specimen book.
        It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of
        Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
        software like Aldus PageMaker including versions of Lorem Ipsum.</P>
    </div>
    <div class="col-md-4">
      <div class="page-header">
        <h2>Sub sub subtitulo</h2>
      </div>
      <p>Lorem Ipsum is simply dummy text of
        the printing and typesetting industry.
        Lorem Ipsum has been the industry's standard dummy
        text ever since the 1500s, when an unknown printer
        took a galley of type and scrambled it to make a type specimen book.
        It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of
        Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
        software like Aldus PageMaker including versions of Lorem Ipsum.</P>
      <div class="page-header">
        <h2>Sub ... Subtitulos</h2>
      </div>
      <p>Lorem Ipsum is simply dummy text of
        the printing and typesetting industry.
        Lorem Ipsum has been the industry's standard dummy
        text ever since the 1500s, when an unknown printer
        took a galley of type and scrambled it to make a type specimen book.
        It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of
        Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
        software like Aldus PageMaker including versions of Lorem Ipsum.</P>
      <a href="https://www.acmilan.com/en">
        <img src="" >
      </a>
      <hr>
      <br>

      <img src="">
      <ul>
        <li>Item 1</li>
        <li>Item 2</li>
        <li>Item 3</li>
      </ul>
    </div>
  </div>
</div>